package Vista.Administrador;

import Controlador.BBDDDAO;
import Controlador.PacienteDAO;
import Controlador.TecnicoDAO;
import Modelo.BBDD;
import Modelo.Paciente;
import Modelo.Tecnico;
import Vista.Tecnico.Paciente.VentanaPaciente;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class VentanaAñadirPacienteconAdmin extends javax.swing.JFrame {

    BBDD bbdd = new BBDD();
    BBDDDAO bddao = new BBDDDAO();

    Tecnico tecnico = new Tecnico();
    TecnicoDAO tecnicoDAO = new TecnicoDAO();
    
    Paciente paciente = new Paciente();
    PacienteDAO pacienteDAO = new PacienteDAO();

    public VentanaAñadirPacienteconAdmin() {
        initComponents();
        llenarJcbTecnicos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        brnCrear = new javax.swing.JButton();
        txtRut = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        txtContraseña = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jcbTecnicos = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Rut");

        jLabel2.setText("Nombre");

        jLabel3.setText("Diagnostico");

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        brnCrear.setText("Añadir");
        brnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brnCrearActionPerformed(evt);
            }
        });

        jLabel4.setText("Creacion de usuarios");

        jLabel5.setText("A que tecnico va");

        jcbTecnicos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(113, 113, 113))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(brnCrear)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(5, 5, 5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSalir, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtContraseña, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtUsuario)
                    .addComponent(txtRut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(jcbTecnicos, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel4)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jcbTecnicos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir)
                    .addComponent(brnCrear))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void brnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brnCrearActionPerformed
        int rut;
        String usuario, contraseña;
        rut = Integer.parseInt(txtRut.getText());
        usuario = txtUsuario.getText();
        contraseña = txtContraseña.getText();
        int run_tec_run = manejarSeleccionTecnico();

        Paciente tec = new Paciente(rut, run_tec_run, usuario, contraseña);
        TecnicoDAO tecDAO = new TecnicoDAO();

        if (txtRut.getText().length() > 0 && txtUsuario.getText().length() > 0 && txtContraseña.getText().length() > 0) {
            if (pacienteDAO.ValidarPac(rut, run_tec_run) == null) {
                pacienteDAO.ingresarPaciente(tec);
                JOptionPane.showMessageDialog(this, usuario + " añadido correctamente");

            } else {
                JOptionPane.showMessageDialog(rootPane, "Ese paciente ya está registrado");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Ingresa datos validos porfavor");
        }
    }//GEN-LAST:event_brnCrearActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        Cpanel VAIE = new Cpanel();

        VAIE.setResizable(false);
        VAIE.setLocationRelativeTo(null);
        VAIE.setTitle("Técnicos");
        VAIE.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        VAIE.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    public void llenarJcbTecnicos() {

        jcbTecnicos.setEnabled(true);
        jcbTecnicos.removeAllItems();
        ArrayList<Tecnico> lista = tecnicoDAO.obtenerTodos();
        for (Tecnico tmp : lista) {
            String items = tmp.getRun_tec() + " - " + tmp.getUsuario();
            jcbTecnicos.addItem(String.valueOf(items));
        }
    }

    public int manejarSeleccionTecnico() {
        String seleccionado = (String) jcbTecnicos.getSelectedItem();
        if (seleccionado != null && seleccionado.contains("-")) {
            String[] partes = seleccionado.split(" - ");
            int numero = Integer.parseInt(partes[0].trim()); 
            return numero;
        } else {
            return -1;
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brnCrear;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JComboBox<String> jcbTecnicos;
    private javax.swing.JTextField txtContraseña;
    private javax.swing.JTextField txtRut;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
