package Vista.Tecnico.Paciente.ProcedimientosMedicamentos;

import Controlador.MedicamentoDAO;
import Modelo.Medicamento;
import java.sql.Date;
import java.util.Random;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JButton;

public class VentanaCrearMedicamento extends javax.swing.JFrame {

    Medicamento medicamento = new Medicamento();
    MedicamentoDAO medicamentoDAO = new MedicamentoDAO();
    Random rand = new Random();

    /**
     * Creates new form VentanaCrearMedicamento
     */
    public VentanaCrearMedicamento() {
        initComponents();

        ButtonGroup grupoDeRadios = new ButtonGroup();

        grupoDeRadios.add(jrb8);
        grupoDeRadios.add(jrb12);
        grupoDeRadios.add(jrb24);

        validarRadios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jCheckBox2 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jdcFecha = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jcbCronico = new javax.swing.JCheckBox();
        jrb8 = new javax.swing.JRadioButton();
        jrb24 = new javax.swing.JRadioButton();
        jrb12 = new javax.swing.JRadioButton();

        jTextField2.setText("jTextField2");

        jCheckBox2.setText("jCheckBox2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre del medicamento");

        jLabel2.setText("Cada cuantas horas debe tomarlo?");

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        jLabel3.setText("Hasta cuando debe tomarlo? ");

        jcbCronico.setText("El paciente es cronico?");
        jcbCronico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbCronicoActionPerformed(evt);
            }
        });

        jrb8.setText("8");
        jrb8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb8ActionPerformed(evt);
            }
        });

        jrb24.setText("24");

        jrb12.setText("12");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jcbCronico))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jrb8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jrb12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jrb24)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jdcFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAgregar)
                        .addGap(243, 243, 243)
                        .addComponent(btnVolver)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(jLabel4)
                .addContainerGap(231, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jdcFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrb8)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jrb24)
                        .addComponent(jrb12)
                        .addComponent(jLabel2)))
                .addGap(44, 44, 44)
                .addComponent(jcbCronico)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVolver)
                    .addComponent(btnAgregar))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        VentanaMain VM = new VentanaMain();

        VM.setResizable(false);
        VM.setLocationRelativeTo(null);
        VM.setTitle("Medicamentos y Procedimientos");
        VM.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);

        VM.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed

        Date fecha;

        if (txtNombre.getText().trim().length() > 0) {
            if (jcbCronico.isSelected()) {
                fecha = null;
            } else {
                java.util.Date temp = jdcFecha.getDate();
                fecha = new java.sql.Date(temp.getTime());
            }

            boolean cronico = jcbCronico.isSelected();
            String nombre_med = txtNombre.getText().trim();
            int id_med = rand.nextInt();
            int ciclo = validarRadios();

            medicamento = new Medicamento(id_med, cronico, ciclo, nombre_med, fecha);
            medicamentoDAO.ingresarMed(medicamento);

            JOptionPane.showMessageDialog(rootPane, (nombre_med + " agregado a los medicamentos"));

            VentanaMain VM = new VentanaMain();

            VM.setResizable(false);
            VM.setLocationRelativeTo(null);
            VM.setTitle("Medicamentos y procedimientos");
            VM.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);

            VM.setVisible(true);

            dispose();

        } else {
            JOptionPane.showMessageDialog(rootPane, "Están mal ingresados los codigos che");
        }

    }//GEN-LAST:event_btnAgregarActionPerformed

    private void jcbCronicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbCronicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbCronicoActionPerformed

    private void jrb8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrb8ActionPerformed

    public int validarRadios() {

        if (jrb8.isSelected()) {
            return 8;
        }
        if (jrb12.isSelected()) {
            return 12;
        }
        if (jrb24.isSelected()) {
            return 24;
        } else {
            return 0;
        }
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnVolver;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JCheckBox jcbCronico;
    private com.toedter.calendar.JDateChooser jdcFecha;
    private javax.swing.JRadioButton jrb12;
    private javax.swing.JRadioButton jrb24;
    private javax.swing.JRadioButton jrb8;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
