package Vista;

import Controlador.*;
import Modelo.BBDD;
import Vista.Administrador.VentanaAdmin;
import Vista.Paciente.VentanaPaciente;
import Vista.Tecnico.VentanaTecnico;
import javax.swing.JOptionPane;

public class VentanaLogin extends javax.swing.JFrame {

    public VentanaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLogin = new javax.swing.JPanel();
        txtContraseña = new javax.swing.JPasswordField();
        btnLimpiar = new javax.swing.JButton();
        lblUsuario = new javax.swing.JLabel();
        lblPass = new javax.swing.JLabel();
        btnIngresar = new javax.swing.JButton();
        txtUsuario = new javax.swing.JTextField();
        mnbrVP = new javax.swing.JMenuBar();
        menuUsuario = new javax.swing.JMenu();
        menuActDatos = new javax.swing.JMenuItem();
        menuCerrarSesion = new javax.swing.JMenuItem();
        menuNav = new javax.swing.JMenu();
        menuNavReg = new javax.swing.JMenuItem();
        menuNavPac = new javax.swing.JMenuItem();
        menuNavTec = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Enfermería a domicilio");
        setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        setMinimumSize(new java.awt.Dimension(750, 650));
        setName("VPrincipal"); // NOI18N
        setPreferredSize(new java.awt.Dimension(750, 650));
        setResizable(false);
        setSize(new java.awt.Dimension(750, 650));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                frameOpenWindow(evt);
            }
        });

        panelLogin.setBackground(new java.awt.Color(255, 255, 255));

        txtContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContraseñaActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.setSelected(true);
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        lblUsuario.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblUsuario.setText("Usuario:");

        lblPass.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblPass.setText("Contraseña:");

        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        txtUsuario.setText(" ");
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLoginLayout = new javax.swing.GroupLayout(panelLogin);
        panelLogin.setLayout(panelLoginLayout);
        panelLoginLayout.setHorizontalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelLoginLayout.createSequentialGroup()
                        .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPass)
                            .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        panelLoginLayout.setVerticalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPass)
                    .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        mnbrVP.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        menuUsuario.setText("Usuario");

        menuActDatos.setText("Actualizar datos");
        menuActDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActDatosActionPerformed(evt);
            }
        });
        menuUsuario.add(menuActDatos);

        menuCerrarSesion.setText("Cerrar sesión");
        menuCerrarSesion.setToolTipText("No hay sesión iniciada");
        menuCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCerrarSesionActionPerformed(evt);
            }
        });
        menuCerrarSesion.setEnabled(false);
        menuUsuario.add(menuCerrarSesion);

        mnbrVP.add(menuUsuario);

        menuNav.setText("Navegar");

        menuNavReg.setText("Registro");
        menuNavReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNavRegActionPerformed(evt);
            }
        });
        menuNav.add(menuNavReg);

        menuNavPac.setText("Pacientes");
        menuNavPac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNavPacActionPerformed(evt);
            }
        });
        menuNav.add(menuNavPac);

        menuNavTec.setText("Técnicos");
        menuNavTec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNavTecActionPerformed(evt);
            }
        });
        menuNav.add(menuNavTec);

        mnbrVP.add(menuNav);

        setJMenuBar(mnbrVP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(panelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(104, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(panelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        String user;
        char[] psswd;
        user = txtUsuario.getText();
        psswd = txtContraseña.getPassword();

        String str;
        str = new String(psswd);
        
        AuxiliarDAO aux = new AuxiliarDAO();

        String queryAdm = "Select id_admin from tbAdministrador WHERE usuario = ? AND passwrd = ?";
        int validA = aux.validarUser(user, psswd, queryAdm, aux);

        String queryTec = "Select run_tec from tbTecnico WHERE usuario = ? AND passwrd = ?";
        int validT = aux.validarUser(user, psswd, queryTec, aux);

        BBDDDAO bd = new BBDDDAO();
        BBDD bede = new BBDD();

        bede.setOrigen(1);

        if (validA != -1) {            
            bede.setAdministrador(validA);
            bd.modificarAdministrador(bede);
            
            VentanaAdmin v = new VentanaAdmin();

            v.setLocationRelativeTo(null);
            v.setResizable(false);
            v.setVisible(true);

            this.setVisible(false);

        } else if (validT != -1) {

            bede.setTecnico(validT);
            bd.modificarTecnico(bede);

            VentanaTecnico v = new VentanaTecnico();

            v.setLocationRelativeTo(null);
            v.setResizable(false);
            v.setVisible(true);

            this.setVisible(false);

        } else {
            JOptionPane.showMessageDialog(null, "Usuario o contraseña incorrectos.");
            btnLimpiar.doClick();
        }
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtUsuario.setText("");
        txtContraseña.setText("");

        txtUsuario.requestFocus();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void menuActDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActDatosActionPerformed
        VistaActUsuario v;
        v = new VistaActUsuario();

        v.setLocationRelativeTo(null);

        v.setVisible(true);
    }//GEN-LAST:event_menuActDatosActionPerformed

    private void menuCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCerrarSesionActionPerformed
        int choice = JOptionPane.showConfirmDialog(this, "¿Desea cerrar?", "Cerrar sesión", JOptionPane.OK_CANCEL_OPTION);

        if (choice == 0) {
            VentanaLogin v = new VentanaLogin();

            v.setLocationRelativeTo(null);
            v.setResizable(false);
            v.setVisible(true);
        }
        
    }//GEN-LAST:event_menuCerrarSesionActionPerformed

    private void menuNavRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNavRegActionPerformed
        VentanaDatos v = new VentanaDatos();

        v.setLocationRelativeTo(null);
        v.setResizable(false);
        v.setVisible(true);

        this.setVisible(false);
        
    }//GEN-LAST:event_menuNavRegActionPerformed

    private void menuNavPacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNavPacActionPerformed
        VentanaPaciente v = new VentanaPaciente();

        v.setResizable(false);
        v.setLocationRelativeTo(null);
        v.setVisible(true);

        this.setVisible(false);
    }//GEN-LAST:event_menuNavPacActionPerformed

    private void menuNavTecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNavTecActionPerformed
        VentanaManejoTec v = new VentanaManejoTec();

        v.setLocationRelativeTo(null);
        v.setResizable(false);
        v.setVisible(true);

        this.setVisible(false);
    }//GEN-LAST:event_menuNavTecActionPerformed

    private void txtContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContraseñaActionPerformed
    }//GEN-LAST:event_txtContraseñaActionPerformed

    private void frameOpenWindow(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_frameOpenWindow
        btnLimpiar.doClick();
    }//GEN-LAST:event_frameOpenWindow

    public static void main(String[] args) {
        
        VentanaLogin v = new VentanaLogin();

        v.setResizable(false);
        v.setLocationRelativeTo(null);
        v.setTitle("Inicio");
        v.setDefaultCloseOperation(EXIT_ON_CLOSE);

        v.setVisible(true);

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JMenuItem menuActDatos;
    private javax.swing.JMenuItem menuCerrarSesion;
    private javax.swing.JMenu menuNav;
    private javax.swing.JMenuItem menuNavPac;
    private javax.swing.JMenuItem menuNavReg;
    private javax.swing.JMenuItem menuNavTec;
    private javax.swing.JMenu menuUsuario;
    private javax.swing.JMenuBar mnbrVP;
    private javax.swing.JPanel panelLogin;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
