/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Actualizadores;

import Controlador.TecnicoDAO;
import Controlador.BBDDDAO;
import Controlador.PacienteDAO;
import Modelo.BBDD;
import Modelo.Paciente;
import Modelo.Tecnico;
import Vista.Administrador.Cpanel;
import javax.swing.JOptionPane;

/**
 *
 * @author Snozz
 */
public class ActualizarPaciente extends javax.swing.JFrame {

    Paciente tecnico = new Paciente();
    PacienteDAO tecnicoDAO = new PacienteDAO();

    BBDD bd = new BBDD();
    BBDDDAO bdDAO = new BBDDDAO();

    /**
     * Creates new form ActualizarTecnico
     */
    public ActualizarPaciente() {
        initComponents();
        ActualizarRun();
        ActualizarUser();
        ActualizarDiagnostico();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDiagnostico = new javax.swing.JButton();
        btnRun = new javax.swing.JButton();
        btnUsuario = new javax.swing.JButton();
        jbVolver = new javax.swing.JButton();
        jRun = new javax.swing.JLabel();
        txtDiagnostico = new javax.swing.JLabel();
        jUser = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnDiagnostico.setText("Cambiar");
        btnDiagnostico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiagnosticoActionPerformed(evt);
            }
        });

        btnRun.setText("Cambiar");
        btnRun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRunActionPerformed(evt);
            }
        });

        btnUsuario.setText("Cambiar");
        btnUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuarioActionPerformed(evt);
            }
        });

        jbVolver.setText("Volver");
        jbVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVolverActionPerformed(evt);
            }
        });

        jRun.setText("Run");

        txtDiagnostico.setText("Diagnostico");

        jUser.setText("Usuario");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jUser)
                    .addComponent(jRun)
                    .addComponent(txtDiagnostico))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jbVolver)
                        .addGap(60, 60, 60))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnUsuario)
                        .addGap(84, 84, 84))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRun)
                            .addComponent(btnDiagnostico))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRun)
                    .addComponent(btnRun))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jUser)
                    .addComponent(btnUsuario))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDiagnostico)
                    .addComponent(btnDiagnostico))
                .addGap(68, 68, 68)
                .addComponent(jbVolver)
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDiagnosticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiagnosticoActionPerformed

        String cambioDiagnostico = JOptionPane.showInputDialog("¿Que diagnostico le vas a poner?").trim();
        String diagnosticoOriginal = tecnicoDAO.buscarPac(bdDAO.buscar().getPaciente()).getDiagn();

            int buffer = bdDAO.buscar().getPaciente();
            Paciente tec = tecnicoDAO.buscarPac(buffer);
            tec.setDiagn(cambioDiagnostico);
            tecnicoDAO.modificarPaciente(tec, buffer);

            bd.setPaciente(buffer);
            bdDAO.modificarPaciente(bd);

            JOptionPane.showMessageDialog(rootPane, "Diagnostico cambiado");
            ActualizarDiagnostico();


    }//GEN-LAST:event_btnDiagnosticoActionPerformed

    private void btnRunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRunActionPerformed

        int cambio = Integer.parseInt(JOptionPane.showInputDialog("¿Que rut le vas a poner?").trim());

        if (tecnicoDAO.buscarPac(cambio) == null) {

            int buffer = bdDAO.buscar().getPaciente();

            bd.setPaciente(cambio);
            bdDAO.modificarPaciente(bd);

            Paciente tec = tecnicoDAO.buscarPac(buffer);
            tec.setRun_pac(cambio);

            tecnicoDAO.modificarPaciente(tec, buffer);

            JOptionPane.showMessageDialog(rootPane, "Run cambiado");
            ActualizarRun();

        } else {
            JOptionPane.showMessageDialog(rootPane, "Ese Paciente ya está registrado");
        }
    }//GEN-LAST:event_btnRunActionPerformed

    private void btnUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarioActionPerformed

        String cambio = JOptionPane.showInputDialog("¿Que nombre le vas a poner?").trim();
        int run_pac =  tecnicoDAO.buscarPac(bdDAO.buscar().getPaciente()).getRun_pac();
        int tecnicoAsignado = tecnicoDAO.buscarPac(bdDAO.buscar().getPaciente()).getTec_run_tec();

        if (!tecnicoDAO.ValidarPac(run_pac, tecnicoAsignado).getNombre_p().equalsIgnoreCase(cambio)) {

            int buffer = bdDAO.buscar().getPaciente();
            Paciente tec = tecnicoDAO.buscarPac(buffer);
            tec.setNombre_p(cambio);
            tecnicoDAO.modificarPaciente(tec, buffer);

            bd.setTecnico(buffer);
            bdDAO.modificarTecnico(bd);

            JOptionPane.showMessageDialog(rootPane, "Paciente cambiado");
            ActualizarUser();
        } else {
            JOptionPane.showMessageDialog(rootPane, "El paciente ya tiene ese nombre");
        }


    }//GEN-LAST:event_btnUsuarioActionPerformed

    private void jbVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVolverActionPerformed

        Cpanel VP = new Cpanel();

        VP.setResizable(false);
        VP.setLocationRelativeTo(null);
        VP.setTitle("Cpanel");
        VP.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);

        VP.setVisible(true);
        dispose();
    }//GEN-LAST:event_jbVolverActionPerformed

    public void ActualizarRun() {

        int run = bdDAO.buscar().getPaciente();
        int texto = tecnicoDAO.buscarPac(run).getRun_pac();
        jRun.setText("Run actual: " + texto);
    }

    public void ActualizarUser() {

        int user = bdDAO.buscar().getPaciente();
        String text = tecnicoDAO.buscarPac(user).getNombre_p();
        jUser.setText("Nombre actual: " + text);

    }

    public void ActualizarDiagnostico() {

        int contra = bdDAO.buscar().getPaciente();
        String text = tecnicoDAO.buscarPac(contra).getDiagn();
        txtDiagnostico.setText("Diagnostico actual: " + text);

    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDiagnostico;
    private javax.swing.JButton btnRun;
    private javax.swing.JButton btnUsuario;
    private javax.swing.JLabel jRun;
    private javax.swing.JLabel jUser;
    private javax.swing.JButton jbVolver;
    private javax.swing.JLabel txtDiagnostico;
    // End of variables declaration//GEN-END:variables
}
