/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Actualizadores;

import Controlador.TecnicoDAO;
import Controlador.BBDDDAO;
import Controlador.PacienteDAO;
import Modelo.BBDD;
import Modelo.Paciente;
import Modelo.Tecnico;
import Vista.Administrador.Cpanel;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Snozz
 */
public class ActualizarTecnico extends javax.swing.JFrame {

    Tecnico tecnico = new Tecnico();
    TecnicoDAO tecnicoDAO = new TecnicoDAO();

    Paciente paciente = new Paciente();
    PacienteDAO pacienteDAO = new PacienteDAO();

    BBDD bd = new BBDD();
    BBDDDAO bdDAO = new BBDDDAO();

    /**
     * Creates new form ActualizarTecnico
     */
    public ActualizarTecnico() {
        initComponents();
        ActualizarRun();
        ActualizarUser();
        ActualizarConstraseña();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnContraseña = new javax.swing.JButton();
        btnRun = new javax.swing.JButton();
        btnUsuario = new javax.swing.JButton();
        jbVolver = new javax.swing.JButton();
        jRun = new javax.swing.JLabel();
        jlContraseña = new javax.swing.JLabel();
        jUser = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnContraseña.setText("Cambiar");
        btnContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContraseñaActionPerformed(evt);
            }
        });

        btnRun.setText("Cambiar");
        btnRun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRunActionPerformed(evt);
            }
        });

        btnUsuario.setText("Cambiar");
        btnUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuarioActionPerformed(evt);
            }
        });

        jbVolver.setText("Volver");
        jbVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVolverActionPerformed(evt);
            }
        });

        jRun.setText("Run");

        jlContraseña.setText("Contraseña");

        jUser.setText("Usuario");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jUser)
                    .addComponent(jRun)
                    .addComponent(jlContraseña))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jbVolver)
                        .addGap(60, 60, 60))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnUsuario)
                        .addGap(84, 84, 84))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRun)
                            .addComponent(btnContraseña))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRun)
                    .addComponent(btnRun))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jUser)
                    .addComponent(btnUsuario))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlContraseña)
                    .addComponent(btnContraseña))
                .addGap(68, 68, 68)
                .addComponent(jbVolver)
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContraseñaActionPerformed

        String cambio = JOptionPane.showInputDialog("¿Que contraseña le vas a poner?").trim();
        String user = tecnicoDAO.BuscarTecnicoPorRut(bdDAO.buscar().getTecnico()).getUsuario();

        if (tecnicoDAO.ValidarTec(user, cambio) == null) {

            int buffer = bdDAO.buscar().getTecnico();
            Tecnico tec = tecnicoDAO.BuscarTecnicoPorRut(buffer);
            tec.setPasswrd(cambio);
            tecnicoDAO.modificarTecnicoConRun(tec, buffer);

            bd.setTecnico(buffer);
            bdDAO.modificarTecnico(bd);

            JOptionPane.showMessageDialog(rootPane, "Contraseña cambiada");
            ActualizarConstraseña();
    }                                          
        else {
            JOptionPane.showMessageDialog(rootPane, "Ya hay un user con esas credenciales");
        }

    }//GEN-LAST:event_btnContraseñaActionPerformed

    private void btnRunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRunActionPerformed

        int cambio = Integer.parseInt(JOptionPane.showInputDialog("¿Que rut le vas a poner?").trim());

        if (tecnicoDAO.BuscarTecnicoPorRut(cambio) == null) {

            int buffer = bdDAO.buscar().getTecnico();

            bd.setTecnico(cambio);
            bdDAO.modificarTecnico(bd);

            Tecnico tec = tecnicoDAO.BuscarTecnicoPorRut(buffer);
            tec.setRun_tec(cambio);

            tecnicoDAO.modificarTecnicoConRun(tec, buffer);

            JOptionPane.showMessageDialog(rootPane, "Run cambiado");
            ActualizarRun();

        } else {
            JOptionPane.showMessageDialog(rootPane, "Ese Tecnico ya está registrado");
        }
    }//GEN-LAST:event_btnRunActionPerformed

    private void btnUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarioActionPerformed

        String cambio = JOptionPane.showInputDialog("¿Que nombre le vas a poner?").trim();
        String contraseña = tecnicoDAO.BuscarTecnicoPorRut(bdDAO.buscar().getTecnico()).getPasswrd();

        if (tecnicoDAO.ValidarTec(cambio, contraseña) == null) {

            int buffer = bdDAO.buscar().getTecnico();
            Tecnico tec = tecnicoDAO.BuscarTecnicoPorRut(buffer);
            tec.setUsuario(cambio);
            tecnicoDAO.modificarTecnicoConRun(tec, buffer);

            bd.setTecnico(buffer);
            bdDAO.modificarTecnico(bd);

            JOptionPane.showMessageDialog(rootPane, "Usuario cambiado");
            ActualizarUser();
    }//GEN-LAST:event_btnUsuarioActionPerformed
        else {
            JOptionPane.showMessageDialog(rootPane, "Ese Tecnico ya existe");
        }
    }
    private void jbVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVolverActionPerformed

        Cpanel VP = new Cpanel();

        VP.setResizable(false);
        VP.setLocationRelativeTo(null);
        VP.setTitle("Actualizar Tecnico");
        VP.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);

        VP.setVisible(true);
        dispose();
    }//GEN-LAST:event_jbVolverActionPerformed

    public void ActualizarRun() {

        int ee = bdDAO.buscar().getTecnico();
        int run = tecnicoDAO.BuscarTecnicoPorRut(ee).getRun_tec();
        jRun.setText("Run actual: " + run);
    }

    public void ActualizarUser() {

        int tecnico = bdDAO.buscar().getTecnico();
        String user = tecnicoDAO.BuscarTecnicoPorRut(tecnico).getUsuario();
        jUser.setText("Nombre actual: " + user);

    }

    public void ActualizarConstraseña() {

        int tecnico = bdDAO.buscar().getTecnico();
        String contraseña = tecnicoDAO.BuscarTecnicoPorRut(tecnico).getPasswrd();
        jlContraseña.setText("Contraseña actual: " + contraseña);

    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContraseña;
    private javax.swing.JButton btnRun;
    private javax.swing.JButton btnUsuario;
    private javax.swing.JLabel jRun;
    private javax.swing.JLabel jUser;
    private javax.swing.JButton jbVolver;
    private javax.swing.JLabel jlContraseña;
    // End of variables declaration//GEN-END:variables
}
